name: Build for macOS

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-15, macos-15-intel]
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Git describe
      id: ghd
      uses: proudust/gh-describe@v2

    - name: Cache build env
      id: cache-build-env
      uses: actions/cache@v4
      with:
        path: swan-build/macos/pfx
        key: ${{matrix.os}}-build-env-v1

    - name: 'Compile Project: SWAN'
      run: ./swan-build/macos/build-swan.sh "${{steps.ghd.outputs.describe}}"

    - name: Package
      run: |
        mkdir artifacts
        mv swan-build/macos/out "artifacts/swan_${{runner.os}}-${{runner.arch}}_${{steps.ghd.outputs.describe}}"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: swan_${{runner.os}}-${{runner.arch}}_${{steps.ghd.outputs.describe}}
        path: artifacts
        include-hidden-files: true
